version: '3.8'
services:
  # db:
  #   # image: postgres:15
  #   build: .
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - '5432:5432'
  #   volumes: 
  #     - ./db:/var/lib/postgresql/data

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbbert
      POSTGRES_PASSWORD: dbbert
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db_init/postgres_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db_init/mysql_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"


   